#Nome da pipeline
name: Run Basic Tests

#Gatilho da pipeline
on:
  pull_request:
    branches: [master]

jobs:
    cypress-run:
               #máquina onde será executado a pipeline
               run-on: ubuntu-latest
        steps: 
              # Clone do projeto
            - name: Checkout/Clone do projeto
              uses: actions/checkout@v4

              # Se for necessário adicionar algo no projeto pode ser configurado aqui
            - name: instalar dependencias no projeto
              run: echo "Instalando alguma coisa que for necessário"  

              # Execução dos testes na pipeline
            - name: Executar testes 
              uses: cypress-io/github-action@v6
              with:
                record: true
              env:
                CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

            - name: upload relatorio de testes
              uses: actions/upload-artifact@v4
              with:
                name: Relatório
                path: cypress\reports\html
